site_name: Gateway Integrations Guide
theme:
    name: material
    #custom_dir: docs/overrides
    palette:
        scheme: hdruk
    logo: images/logo.png
    favicon: images/favicon.png
    features:
        - navigation.footer
        - navigation.instant
        - navigation.expand
        - content.code.copy
        - content.code.annotate
        - toc.follow
extra_css:
    - stylesheets/custom.css

nav:
    - Home: index.md
    - Gateway 2.0:
          - API Management: fe-creating-an-app.md
          - FMA Setup: fe-creating-fma.md
    - Metadata:
          - Creating metadata: creating-metadata.md
          - Validating metadata: metadata-validation.md
    - Using the API:
          - Creating a dataset: creating-a-dataset.md
          - Retrieving a dataset: retrieving-a-dataset.md
          - Update a dataset: updating-a-dataset.md
          - Deleting a dataset: deleting-a-dataset.md
plugins:
    - search

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
