site_name: Gateway Integrations Guide
theme:
    name: material
    #custom_dir: docs/overrides
    palette:
        scheme: hdruk
    logo: images/logo.png
    favicon: images/favicon.png
    features:
        - navigation.footer
        - navigation.instant
        - navigation.expand
        - content.code.copy
        - content.code.annotate
        - toc.follow
extra_css:
    - stylesheets/custom.css

nav:
    - Home: index.md
    - Gateway 2.0:
          - Login: fe-login.md
          - API Management: fe-creating-an-app.md
          - FMA Setup: fe-creating-fma.md
    - Metadata:
          - Create: creating-metadata.md
          - Validate: metadata-validation.md
          - Exemplars: example-metadata.md
    - Using the API:
          - Datasets:
                - Create: creating-a-dataset.md
                - Retrieve: retrieving-a-dataset.md
                - Update: updating-a-dataset.md
                - Delete: deleting-a-dataset.md
    - Using FMA:
          - Test Server Example: fma-test-server.md
plugins:
    - search

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - attr_list
    - md_in_html
